// <auto-generated />
namespace WebBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hotels9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hotels9));
        
        string IMigrationMetadata.Id
        {
            get { return "202305281416371_hotels9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
